In [1]:
import pandas as pd
import numpy as np

In [2]:
#pip install openpyxl

In [ ]:
data= pd.read_csv("data/final_concatenated_data.csv")
data

,Unnamed: 0,date,S199,S200,S332B,S332BN,S332C,S332D,S332DX1,S12A,...,NP205_rain,NP205_stage,P33_rain,P33_stage,NP205_PET,P33_PET,G620_water_level,SWEVER4_stage,TSH_stage,NP62_stage
0,0,10/16/2020,242.17,279.69,218.42,218.42,445.77,481.38,0.0,460,...,2.28,6.925,0.106,7.133,2.09,2.09,5.92,2.92,3.03,4.04
1,1,10/17/2020,296.05,294.85,265.13,265.13,587.35,556.24,0.0,490,...,0.01,7.025,0.000,7.133,3.87,3.87,5.97,2.95,3.08,4.05
2,2,10/18/2020,277.85,294.24,264.23,264.23,514.45,503.14,0.0,472,...,0.00,7.008,0.088,7.138,3.51,3.51,5.98,2.93,3.06,4.05
3,3,10/19/2020,224.13,294.72,264.39,264.39,491.06,537.91,0.0,466,...,0.11,6.986,0.256,7.167,1.98,1.98,5.98,2.91,3.05,4.06
4,4,10/20/2020,260.51,295.06,263.38,263.38,489.25,558.77,0.0,472,...,0.37,6.977,0.678,7.195,1.27,1.27,5.99,2.90,3.06,4.11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1406,1406,8/22/2024,297.72,294.23,0.17,0.17,30.02,559.39,0.0,358,...,1.72,7.289,0.050,7.466,2.75,2.75,6.13,2.85,2.78,3.88
1407,1407,8/23/2024,240.47,293.74,0.45,0.45,0.29,491.92,0.0,375,...,0.04,7.360,0.000,7.447,2.75,2.75,6.18,2.90,2.81,3.88
1408,1408,8/24/2024,242.45,293.75,0.00,0.00,0.00,439.40,0.0,377,...,0.00,7.360,0.010,7.435,2.75,2.75,6.20,2.88,2.80,3.88
1409,1409,8/25/2024,286.80,294.24,0.00,0.00,0.00,470.49,0.0,380,...,0.00,7.345,0.270,7.440,2.75,2.75,6.19,2.86,2.80,3.98
1410,1410,8/26/2024,298.19,295.13,0.36,0.36,0.00,527.05,0.0,387,...,0.00,7.320,0.660,7.470,2.75,2.75,6.20,2.85,2.80,4.03

In [39]:
# Convert 'date' column to proper datetime format
data['date'] = pd.to_datetime(data['date'])

# Verify the column types to confirm the 'date' is now datetime
print(data.info())

# When displaying or exporting, you can format the date as MM/DD/YYYY
data['formatted_date'] = data['date'].dt.strftime('%m/%d/%Y')

# Print the first few rows to see the formatted date
print(data[['date', 'formatted_date']])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1411 entries, 0 to 1410
Data columns (total 39 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1411 non-null   int64
 1   date              1411 non-null   datetime64[ns]
 2   S199              1411 non-null   float64
 3   S200              1411 non-null   float64
 4   S332B             1411 non-null   float64
 5   S332BN            1411 non-null   float64
 6   S332C             1411 non-null   float64
 7   S332D             1411 non-null   float64
 8   S332DX1           1411 non-null   float64
 9   S12A              1411 non-null   int64
 10  S12B              1411 non-null   int64
 11  S12C              1411 non-null   int64
 12  S12D              1411 non-null   int64
 13  S333              1411 non-null   float64
 14  S333N             1411 non-null   float64
 15  S334              1411 non-null   float64
 16  S343A             1411 non-null   float64
 17  S343B             1411 non-null   float64
 18  S344              1411 non-null   float64
 19  S356              1411 non-null   float64
 20  S18C_S            1411 non-null   float64
 21  S12A_T            1411 non-null   float64
 22  S12C_T            1411 non-null   float64
 23  S12D_T            1411 non-null   float64
 24  S12B_T            1411 non-null   float64
 25  S333_T            1411 non-null   float64
 26  S334_H            1411 non-null   float64
 27  NESRS1            1411 non-null   float64
 28  NESRS2            1411 non-null   float64
 29  NP205_rain        1411 non-null   float64
 30  NP205_stage       1411 non-null   float64
 31  P33_rain          1411 non-null   float64
 32  P33_stage         1411 non-null   float64
 33  NP205_PET         1411 non-null   float64
 34  P33_PET           1411 non-null   float64
 35  G620_water_level  1411 non-null   float64
 36  SWEVER4_stage     1411 non-null   float64
 37  TSH_stage         1411 non-null   float64
 38  NP62_stage        1411 non-null   float64
dtypes: datetime64[ns](1), float64(33), int64(5)
memory usage: 430.0 KB
None
           date formatted_date
0    2020-10-16     10/16/2020
1    2020-10-17     10/17/2020
2    2020-10-18     10/18/2020
3    2020-10-19     10/19/2020
4    2020-10-20     10/20/2020
...         ...            ...
1406 2024-08-22     08/22/2024
1407 2024-08-23     08/23/2024
1408 2024-08-24     08/24/2024
1409 2024-08-25     08/25/2024
1410 2024-08-26     08/26/2024

[1411 rows x 2 columns]

In [40]:
# Drop the 'formatted_date' column if not needed
data = data.drop(columns=['Unnamed: 0','formatted_date'])

data['date'] = data['date'].dt.strftime('%m/%d/%Y')

# Check the data to confirm the index
data

,date,S199,S200,S332B,S332BN,S332C,S332D,S332DX1,S12A,S12B,...,NP205_rain,NP205_stage,P33_rain,P33_stage,NP205_PET,P33_PET,G620_water_level,SWEVER4_stage,TSH_stage,NP62_stage
0,10/16/2020,242.17,279.69,218.42,218.42,445.77,481.38,0.0,460,382,...,2.28,6.925,0.106,7.133,2.09,2.09,5.92,2.92,3.03,4.04
1,10/17/2020,296.05,294.85,265.13,265.13,587.35,556.24,0.0,490,405,...,0.01,7.025,0.000,7.133,3.87,3.87,5.97,2.95,3.08,4.05
2,10/18/2020,277.85,294.24,264.23,264.23,514.45,503.14,0.0,472,394,...,0.00,7.008,0.088,7.138,3.51,3.51,5.98,2.93,3.06,4.05
3,10/19/2020,224.13,294.72,264.39,264.39,491.06,537.91,0.0,466,392,...,0.11,6.986,0.256,7.167,1.98,1.98,5.98,2.91,3.05,4.06
4,10/20/2020,260.51,295.06,263.38,263.38,489.25,558.77,0.0,472,399,...,0.37,6.977,0.678,7.195,1.27,1.27,5.99,2.90,3.06,4.11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1406,08/22/2024,297.72,294.23,0.17,0.17,30.02,559.39,0.0,358,250,...,1.72,7.289,0.050,7.466,2.75,2.75,6.13,2.85,2.78,3.88
1407,08/23/2024,240.47,293.74,0.45,0.45,0.29,491.92,0.0,375,265,...,0.04,7.360,0.000,7.447,2.75,2.75,6.18,2.90,2.81,3.88
1408,08/24/2024,242.45,293.75,0.00,0.00,0.00,439.40,0.0,377,268,...,0.00,7.360,0.010,7.435,2.75,2.75,6.20,2.88,2.80,3.88
1409,08/25/2024,286.80,294.24,0.00,0.00,0.00,470.49,0.0,380,272,...,0.00,7.345,0.270,7.440,2.75,2.75,6.19,2.86,2.80,3.98
1410,08/26/2024,298.19,295.13,0.36,0.36,0.00,527.05,0.0,387,277,...,0.00,7.320,0.660,7.470,2.75,2.75,6.20,2.85,2.80,4.03

In [ ]:
df = pd.read_excel("data/Results-28days-final.xlsx")
df

,Unnamed: 0,unique_id,ds,y,NBEATS,Informer,DLinear,PatchTST,iTransformer,NLinear,...,TimeMixer,TSMixer,TSMixerx,KAN,TimeGPT,Chronos,TimeLLM,timesfm,Morai,Timer
0,0,G620_water_level,2024-01-29,5.99,5.990283,6.446689,6.009546,5.999596,6.070791,6.007359,...,5.991134,6.003157,6.264428,5.974059,6.136990,5.938847,6.012373,6.348382,6.197403,6.270409
1,1,G620_water_level,2024-01-30,5.97,5.980088,6.428385,6.016413,5.993426,6.077047,5.990021,...,5.986139,5.998189,6.231063,5.963257,6.140436,5.885571,6.030017,6.313637,6.275898,6.288723
2,2,G620_water_level,2024-01-31,5.96,5.970243,6.399603,6.026046,5.985068,6.076143,5.983725,...,5.986710,5.991814,6.217189,5.963891,6.141627,5.877735,6.045658,6.216670,6.106342,6.286527
3,3,G620_water_level,2024-02-01,5.95,5.970322,6.383283,6.014894,5.977842,6.074499,5.977330,...,5.983805,5.985024,6.204739,5.950393,6.141416,5.862428,6.046127,6.201174,6.239551,6.287681
4,4,G620_water_level,2024-02-02,5.94,5.967651,6.365793,6.016383,5.971125,6.065646,5.966732,...,5.985395,5.978159,6.196633,5.949824,6.141319,5.857361,6.028793,6.137943,6.220164,6.266752
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7802,7802,TSH_stage,2024-08-22,2.78,2.705861,3.284135,2.601946,2.604910,2.576495,2.660874,...,2.474700,2.664950,2.742459,2.428840,2.658305,2.778147,2.624435,2.500491,3.002488,2.477719
7803,7803,TSH_stage,2024-08-23,2.81,2.686831,3.247777,2.573833,2.603642,2.580112,2.645612,...,2.459051,2.658326,2.751494,2.403879,2.652127,2.792702,2.610139,2.500567,2.877229,2.486787
7804,7804,TSH_stage,2024-08-24,2.80,2.663762,3.213884,2.560354,2.600448,2.638836,2.631954,...,2.439607,2.649858,2.751780,2.411847,2.637871,2.746403,2.580557,2.444644,2.950637,2.493054
7805,7805,TSH_stage,2024-08-25,2.80,2.652651,3.181499,2.580595,2.604291,2.668186,2.626816,...,2.414936,2.645275,2.754015,2.391036,2.639326,2.719170,2.581784,2.496498,3.037005,2.516393
7806,7806,TSH_stage,2024-08-26,2.80,2.670222,3.163001,2.579090,2.617953,2.727415,2.638371,...,2.394792,2.646476,2.811199,2.361201,2.657450,2.701749,2.584143,2.619833,2.945513,2.533993

In [4]:
# Drop the 'formatted_date' column if not needed
df = df.drop(columns=['Unnamed: 0'])
df

,unique_id,ds,y,NBEATS,Informer,DLinear,PatchTST,iTransformer,NLinear,RMoK,TimeMixer,TSMixer,TSMixerx,KAN,TimeGPT,Chronos,TimeLLM,timesfm,Morai,Timer
0,G620_water_level,2024-01-29,5.99,5.990283,6.446689,6.009546,5.999596,6.070791,6.007359,6.037122,5.991134,6.003157,6.264428,5.974059,6.136990,5.938847,6.012373,6.348382,6.197403,6.270409
1,G620_water_level,2024-01-30,5.97,5.980088,6.428385,6.016413,5.993426,6.077047,5.990021,6.034707,5.986139,5.998189,6.231063,5.963257,6.140436,5.885571,6.030017,6.313637,6.275898,6.288723
2,G620_water_level,2024-01-31,5.96,5.970243,6.399603,6.026046,5.985068,6.076143,5.983725,6.032871,5.986710,5.991814,6.217189,5.963891,6.141627,5.877735,6.045658,6.216670,6.106342,6.286527
3,G620_water_level,2024-02-01,5.95,5.970322,6.383283,6.014894,5.977842,6.074499,5.977330,6.023985,5.983805,5.985024,6.204739,5.950393,6.141416,5.862428,6.046127,6.201174,6.239551,6.287681
4,G620_water_level,2024-02-02,5.94,5.967651,6.365793,6.016383,5.971125,6.065646,5.966732,6.014345,5.985395,5.978159,6.196633,5.949824,6.141319,5.857361,6.028793,6.137943,6.220164,6.266752
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7802,TSH_stage,2024-08-22,2.78,2.705861,3.284135,2.601946,2.604910,2.576495,2.660874,2.541839,2.474700,2.664950,2.742459,2.428840,2.658305,2.778147,2.624435,2.500491,3.002488,2.477719
7803,TSH_stage,2024-08-23,2.81,2.686831,3.247777,2.573833,2.603642,2.580112,2.645612,2.540648,2.459051,2.658326,2.751494,2.403879,2.652127,2.792702,2.610139,2.500567,2.877229,2.486787
7804,TSH_stage,2024-08-24,2.80,2.663762,3.213884,2.560354,2.600448,2.638836,2.631954,2.534780,2.439607,2.649858,2.751780,2.411847,2.637871,2.746403,2.580557,2.444644,2.950637,2.493054
7805,TSH_stage,2024-08-25,2.80,2.652651,3.181499,2.580595,2.604291,2.668186,2.626816,2.519340,2.414936,2.645275,2.754015,2.391036,2.639326,2.719170,2.581784,2.496498,3.037005,2.516393
7806,TSH_stage,2024-08-26,2.80,2.670222,3.163001,2.579090,2.617953,2.727415,2.638371,2.521523,2.394792,2.646476,2.811199,2.361201,2.657450,2.701749,2.584143,2.619833,2.945513,2.533993

In [5]:
## For NP205 stage ###

import pandas as pd
import numpy as np  # Make sure to import numpy

# Assuming df is your DataFrame
unique_id = 'NP205_stage'

# Filter dataset for the unique_id
df_filtered = df[df['unique_id'] == unique_id]

# Extract actual and predicted values
y_true = df_filtered['y']
predicted_columns = ['NBEATS', 'Informer', 'DLinear', 'PatchTST', 'iTransformer', 'NLinear', 'RMoK', 
                     'TimeMixer', 'TSMixer', 'TSMixerx', 'KAN', 'TimeGPT', 'Chronos', 'TimeLLM', 'timesfm', 'Morai', 'Timer']

# Initialize dictionary to store SEDI values
sedi_results = {}

# Define function to calculate SEDI score for a given threshold
def calculate_sedi(true_values, predicted_values, low_threshold, high_threshold):
    yp_low = np.percentile(true_values, low_threshold * 100)
    yp_up = np.percentile(true_values, high_threshold * 100)

    numerator = 0
    denominator = 0
    
    # Loop through each prediction and calculate SEDI
    for true_value, pred_value in zip(true_values, predicted_values):
        true_extreme_low = true_value < yp_low
        true_extreme_up = true_value > yp_up
        pred_extreme_low = pred_value < yp_low
        pred_extreme_up = pred_value > yp_up
        
        if true_extreme_low:
            denominator += 1
        if true_extreme_up:
            denominator += 1
        if true_extreme_low and pred_extreme_low:
            numerator += 1
        if true_extreme_up and pred_extreme_up:
            numerator += 1
    
    # Return SEDI score, avoiding division by zero
    return numerator / denominator if denominator != 0 else 0

# Define percentiles to calculate SEDI for
percentiles = [0.995, 0.90]

# Initialize a dictionary to store SEDI scores for each model and unique_id
sedi_scores_by_id = {}

# Calculate SEDI scores for each model at 99.5th and 90th percentiles
for model in predicted_columns:
    model_scores = []
    for p in percentiles:
        sedi_score = calculate_sedi(y_true, df_filtered[model], 1 - p, p)
        model_scores.append(sedi_score)
    sedi_scores_by_id[model] = model_scores

# Store the calculated SEDI scores for this unique_id
sedi_results[unique_id] = sedi_scores_by_id

# Convert to DataFrame for easy visualization
sedi_df1 = pd.DataFrame(sedi_results[unique_id], index=[f"99.5th ↑", f"90th ↑"])
print(sedi_df1)

            NBEATS  Informer   DLinear  PatchTST  iTransformer   NLinear  \
99.5th ↑  0.000000  0.333333  0.000000  0.000000      0.000000  0.000000
90th ↑    0.261905  0.500000  0.261905  0.190476      0.142857  0.142857

              RMoK  TimeMixer   TSMixer  TSMixerx       KAN  TimeGPT  \
99.5th ↑  0.000000   0.000000  0.000000  0.000000  0.000000  0.00000
90th ↑    0.119048   0.119048  0.142857  0.380952  0.119048  0.02381

           Chronos  TimeLLM   timesfm    Morai  Timer
99.5th ↑  0.666667      0.0  0.000000  0.00000    0.0
90th ↑    0.785714      0.0  0.095238  0.47619    0.0

In [69]:
import pandas as pd
import numpy as np  # Make sure to import numpy

# Assuming df is your DataFrame
unique_id = 'NP205_stage'

# Filter dataset for the unique_id
df_filtered = df[df['unique_id'] == unique_id]

df_filtered

,unique_id,ds,y,NBEATS,Informer,DLinear,PatchTST,iTransformer,NLinear,RMoK,TimeMixer,TSMixer,TSMixerx,KAN,TimeGPT,Chronos,TimeLLM,timesfm,Morai,Timer
1055,NP205_stage,2024-01-29,7.127,7.135194,7.238698,7.141992,7.137944,7.175009,7.144142,7.174661,7.143908,7.137240,7.307901,7.086700,7.235756,7.023329,7.133659,7.340815,7.269594,7.297016
1056,NP205_stage,2024-01-30,7.116,7.123710,7.286937,7.146895,7.131806,7.182275,7.129471,7.163075,7.142182,7.130715,7.286036,7.082682,7.237523,7.039040,7.131574,7.312752,7.317292,7.282616
1057,NP205_stage,2024-01-31,7.105,7.114120,7.318243,7.155584,7.127774,7.184895,7.125630,7.156250,7.147869,7.126416,7.274260,7.088835,7.239537,7.039646,7.138310,7.304362,7.201531,7.285785
1058,NP205_stage,2024-02-01,7.096,7.109529,7.290575,7.143279,7.123622,7.184194,7.117888,7.144182,7.151390,7.120860,7.269679,7.080622,7.240088,7.010786,7.133603,7.310450,7.185257,7.281482
1059,NP205_stage,2024-02-02,7.090,7.102480,7.272428,7.146267,7.120425,7.181314,7.108766,7.136358,7.156549,7.115332,7.263985,7.078706,7.239422,6.993391,7.127891,7.317267,7.224599,7.283624
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1261,NP205_stage,2024-08-22,7.289,6.965040,7.648274,6.227650,6.633997,7.032182,7.017534,7.083467,6.386096,6.926773,7.042697,7.102453,7.023972,7.249594,6.777732,6.026195,7.223845,6.601074
1262,NP205_stage,2024-08-23,7.360,6.938839,7.606879,6.194254,6.630550,7.023626,7.017945,7.057606,6.346909,6.931131,7.031782,7.126645,7.017220,7.391357,6.792298,5.862614,7.269664,6.633044
1263,NP205_stage,2024-08-24,7.360,6.915342,7.567897,6.139271,6.630191,7.007094,7.030148,7.051517,6.293911,6.933712,7.039500,7.168556,7.007457,7.361775,6.754065,5.890214,7.192854,6.676521
1264,NP205_stage,2024-08-25,7.345,6.910272,7.528827,6.208267,6.640713,6.990207,6.996975,7.003969,6.225554,6.939000,7.035943,7.167571,7.008780,7.253472,6.777097,5.899252,7.270527,6.607837
1265,NP205_stage,2024-08-26,7.320,6.929840,7.509916,6.160145,6.645916,6.980223,7.003334,7.007203,6.177473,6.954012,7.111426,7.142991,7.020632,7.175851,6.755639,5.832416,7.266911,6.635284

In [6]:
print(sedi_df1.T)

              99.5th ↑    90th ↑
NBEATS        0.000000  0.261905
Informer      0.333333  0.500000
DLinear       0.000000  0.261905
PatchTST      0.000000  0.190476
iTransformer  0.000000  0.142857
NLinear       0.000000  0.142857
RMoK          0.000000  0.119048
TimeMixer     0.000000  0.119048
TSMixer       0.000000  0.142857
TSMixerx      0.000000  0.380952
KAN           0.000000  0.119048
TimeGPT       0.000000  0.023810
Chronos       0.666667  0.785714
TimeLLM       0.000000  0.000000
timesfm       0.000000  0.095238
Morai         0.000000  0.476190
Timer         0.000000  0.000000

In [7]:
sedi_df1 = sedi_df1.drop("99.5th ↑", axis=0)
sedi_df1

,NBEATS,Informer,DLinear,PatchTST,iTransformer,NLinear,RMoK,TimeMixer,TSMixer,TSMixerx,KAN,TimeGPT,Chronos,TimeLLM,timesfm,Morai,Timer
90th ↑,0.261905,0.5,0.261905,0.190476,0.142857,0.142857,0.119048,0.119048,0.142857,0.380952,0.119048,0.02381,0.785714,0.0,0.095238,0.47619,0.0

In [8]:
import pandas as pd
import numpy as np  # Make sure to import numpy

# Assuming df is your DataFrame
unique_id = 'P33_stage'

# Filter dataset for the unique_id
df_filtered = df[df['unique_id'] == unique_id]

# Extract actual and predicted values
y_true = df_filtered['y']
predicted_columns = ['NBEATS', 'Informer', 'DLinear', 'PatchTST', 'iTransformer', 'NLinear', 'RMoK', 
                     'TimeMixer', 'TSMixer', 'TSMixerx', 'KAN', 'TimeGPT', 'Chronos', 'TimeLLM', 'timesfm','Morai', 'Timer']

# Initialize dictionary to store SEDI values
sedi_results = {}

# Define function to calculate SEDI score for a given threshold
def calculate_sedi(true_values, predicted_values, low_threshold, high_threshold):
    yp_low = np.percentile(true_values, low_threshold * 100)
    yp_up = np.percentile(true_values, high_threshold * 100)

    numerator = 0
    denominator = 0
    
    # Loop through each prediction and calculate SEDI
    for true_value, pred_value in zip(true_values, predicted_values):
        true_extreme_low = true_value < yp_low
        true_extreme_up = true_value > yp_up
        pred_extreme_low = pred_value < yp_low
        pred_extreme_up = pred_value > yp_up
        
        if true_extreme_low:
            denominator += 1
        if true_extreme_up:
            denominator += 1
        if true_extreme_low and pred_extreme_low:
            numerator += 1
        if true_extreme_up and pred_extreme_up:
            numerator += 1
    
    # Return SEDI score, avoiding division by zero
    return numerator / denominator if denominator != 0 else 0

# Define percentiles to calculate SEDI for
percentiles = [0.995, 0.90]

# Initialize a dictionary to store SEDI scores for each model and unique_id
sedi_scores_by_id = {}

# Calculate SEDI scores for each model at 99.5th and 90th percentiles
for model in predicted_columns:
    model_scores = []
    for p in percentiles:
        sedi_score = calculate_sedi(y_true, df_filtered[model], 1 - p, p)
        model_scores.append(sedi_score)
    sedi_scores_by_id[model] = model_scores

# Store the calculated SEDI scores for this unique_id
sedi_results[unique_id] = sedi_scores_by_id

# Convert to DataFrame for easy visualization
sedi_df2 = pd.DataFrame(sedi_results[unique_id], index=[f"99.5th ↑", f"90th ↑"])
print(sedi_df2)

            NBEATS  Informer   DLinear  PatchTST  iTransformer   NLinear  \
99.5th ↑  0.000000  0.500000  0.500000  0.000000      0.000000  0.000000
90th ↑    0.268293  0.487805  0.512195  0.146341      0.243902  0.121951

              RMoK  TimeMixer   TSMixer  TSMixerx       KAN   TimeGPT  \
99.5th ↑  0.000000    0.00000  0.000000  0.500000  0.000000  0.000000
90th ↑    0.097561    0.04878  0.146341  0.829268  0.073171  0.195122

           Chronos  TimeLLM  timesfm     Morai  Timer
99.5th ↑  0.500000      0.0  0.00000  0.000000    0.0
90th ↑    0.658537      0.0  0.02439  0.317073    0.0

In [9]:
print(sedi_df2.T)

              99.5th ↑    90th ↑
NBEATS             0.0  0.268293
Informer           0.5  0.487805
DLinear            0.5  0.512195
PatchTST           0.0  0.146341
iTransformer       0.0  0.243902
NLinear            0.0  0.121951
RMoK               0.0  0.097561
TimeMixer          0.0  0.048780
TSMixer            0.0  0.146341
TSMixerx           0.5  0.829268
KAN                0.0  0.073171
TimeGPT            0.0  0.195122
Chronos            0.5  0.658537
TimeLLM            0.0  0.000000
timesfm            0.0  0.024390
Morai              0.0  0.317073
Timer              0.0  0.000000

In [10]:
sedi_df2 = sedi_df2.drop("99.5th ↑", axis=0)

In [11]:
sedi_df2

,NBEATS,Informer,DLinear,PatchTST,iTransformer,NLinear,RMoK,TimeMixer,TSMixer,TSMixerx,KAN,TimeGPT,Chronos,TimeLLM,timesfm,Morai,Timer
90th ↑,0.268293,0.487805,0.512195,0.146341,0.243902,0.121951,0.097561,0.04878,0.146341,0.829268,0.073171,0.195122,0.658537,0.0,0.02439,0.317073,0.0

In [12]:
import pandas as pd
import numpy as np  # Make sure to import numpy

# Assuming df is your DataFrame
unique_id = 'G620_water_level'

# Filter dataset for the unique_id
df_filtered = df[df['unique_id'] == unique_id]

# Extract actual and predicted values
y_true = df_filtered['y']
predicted_columns = ['NBEATS', 'Informer', 'DLinear', 'PatchTST', 'iTransformer', 'NLinear', 'RMoK', 
                     'TimeMixer', 'TSMixer', 'TSMixerx', 'KAN', 'TimeGPT', 'Chronos', 'TimeLLM', 'timesfm','Morai', 'Timer']

# Initialize dictionary to store SEDI values
sedi_results = {}

# Define function to calculate SEDI score for a given threshold
def calculate_sedi(true_values, predicted_values, low_threshold, high_threshold):
    yp_low = np.percentile(true_values, low_threshold * 100)
    yp_up = np.percentile(true_values, high_threshold * 100)

    numerator = 0
    denominator = 0
    
    # Loop through each prediction and calculate SEDI
    for true_value, pred_value in zip(true_values, predicted_values):
        true_extreme_low = true_value < yp_low
        true_extreme_up = true_value > yp_up
        pred_extreme_low = pred_value < yp_low
        pred_extreme_up = pred_value > yp_up
        
        if true_extreme_low:
            denominator += 1
        if true_extreme_up:
            denominator += 1
        if true_extreme_low and pred_extreme_low:
            numerator += 1
        if true_extreme_up and pred_extreme_up:
            numerator += 1
    
    # Return SEDI score, avoiding division by zero
    return numerator / denominator if denominator != 0 else 0

# Define percentiles to calculate SEDI for
percentiles = [0.995, 0.90]

# Initialize a dictionary to store SEDI scores for each model and unique_id
sedi_scores_by_id = {}

# Calculate SEDI scores for each model at 99.5th and 90th percentiles
for model in predicted_columns:
    model_scores = []
    for p in percentiles:
        sedi_score = calculate_sedi(y_true, df_filtered[model], 1 - p, p)
        model_scores.append(sedi_score)
    sedi_scores_by_id[model] = model_scores

# Store the calculated SEDI scores for this unique_id
sedi_results[unique_id] = sedi_scores_by_id

# Convert to DataFrame for easy visualization
sedi_df3 = pd.DataFrame(sedi_results[unique_id], index=[f"99.5th ↑", f"90th ↑"])
print(sedi_df3)

            NBEATS  Informer   DLinear  PatchTST  iTransformer   NLinear  \
99.5th ↑  0.000000  1.000000  0.000000  0.000000      0.000000  0.000000
90th ↑    0.463415  0.487805  0.390244  0.195122      0.243902  0.146341

              RMoK  TimeMixer   TSMixer  TSMixerx       KAN   TimeGPT  \
99.5th ↑  0.000000   0.000000  0.000000  0.000000  0.000000  0.000000
90th ↑    0.170732   0.341463  0.195122  0.829268  0.341463  0.195122

           Chronos  TimeLLM   timesfm     Morai  Timer
99.5th ↑  0.000000      0.0  1.000000  0.000000    0.0
90th ↑    0.804878      0.0  0.170732  0.487805    0.0

In [13]:
print(sedi_df3.T)

              99.5th ↑    90th ↑
NBEATS             0.0  0.463415
Informer           1.0  0.487805
DLinear            0.0  0.390244
PatchTST           0.0  0.195122
iTransformer       0.0  0.243902
NLinear            0.0  0.146341
RMoK               0.0  0.170732
TimeMixer          0.0  0.341463
TSMixer            0.0  0.195122
TSMixerx           0.0  0.829268
KAN                0.0  0.341463
TimeGPT            0.0  0.195122
Chronos            0.0  0.804878
TimeLLM            0.0  0.000000
timesfm            1.0  0.170732
Morai              0.0  0.487805
Timer              0.0  0.000000

In [14]:
sedi_df3 = sedi_df3.drop("99.5th ↑", axis=0)

In [15]:
sedi_df3

,NBEATS,Informer,DLinear,PatchTST,iTransformer,NLinear,RMoK,TimeMixer,TSMixer,TSMixerx,KAN,TimeGPT,Chronos,TimeLLM,timesfm,Morai,Timer
90th ↑,0.463415,0.487805,0.390244,0.195122,0.243902,0.146341,0.170732,0.341463,0.195122,0.829268,0.341463,0.195122,0.804878,0.0,0.170732,0.487805,0.0

In [16]:
import pandas as pd
import numpy as np  # Make sure to import numpy

# Assuming df is your DataFrame
unique_id = 'NESRS1'

# Filter dataset for the unique_id
df_filtered = df[df['unique_id'] == unique_id]

# Extract actual and predicted values
y_true = df_filtered['y']
predicted_columns = ['NBEATS', 'Informer', 'DLinear', 'PatchTST', 'iTransformer', 'NLinear', 'RMoK', 
                     'TimeMixer', 'TSMixer', 'TSMixerx', 'KAN', 'TimeGPT', 'Chronos', 'TimeLLM', 'timesfm', 'Morai', 'Timer']

# Initialize dictionary to store SEDI values
sedi_results = {}

# Define function to calculate SEDI score for a given threshold
def calculate_sedi(true_values, predicted_values, low_threshold, high_threshold):
    yp_low = np.percentile(true_values, low_threshold * 100)
    yp_up = np.percentile(true_values, high_threshold * 100)

    numerator = 0
    denominator = 0
    
    # Loop through each prediction and calculate SEDI
    for true_value, pred_value in zip(true_values, predicted_values):
        true_extreme_low = true_value < yp_low
        true_extreme_up = true_value > yp_up
        pred_extreme_low = pred_value < yp_low
        pred_extreme_up = pred_value > yp_up
        
        if true_extreme_low:
            denominator += 1
        if true_extreme_up:
            denominator += 1
        if true_extreme_low and pred_extreme_low:
            numerator += 1
        if true_extreme_up and pred_extreme_up:
            numerator += 1
    
    # Return SEDI score, avoiding division by zero
    return numerator / denominator if denominator != 0 else 0

# Define percentiles to calculate SEDI for
percentiles = [0.995, 0.90]

# Initialize a dictionary to store SEDI scores for each model and unique_id
sedi_scores_by_id = {}

# Calculate SEDI scores for each model at 99.5th and 90th percentiles
for model in predicted_columns:
    model_scores = []
    for p in percentiles:
        sedi_score = calculate_sedi(y_true, df_filtered[model], 1 - p, p)
        model_scores.append(sedi_score)
    sedi_scores_by_id[model] = model_scores

# Store the calculated SEDI scores for this unique_id
sedi_results[unique_id] = sedi_scores_by_id

# Convert to DataFrame for easy visualization
sedi_df4 = pd.DataFrame(sedi_results[unique_id], index=[f"99.5th ↑", f"90th ↑"])
print(sedi_df4)

            NBEATS  Informer   DLinear  PatchTST  iTransformer   NLinear  \
99.5th ↑  0.000000  0.000000  0.500000  0.000000      0.000000  0.000000
90th ↑    0.268293  0.512195  0.487805  0.146341      0.243902  0.121951

              RMoK  TimeMixer   TSMixer  TSMixerx       KAN   TimeGPT  \
99.5th ↑  0.000000        0.0  0.000000  0.000000  0.000000  0.000000
90th ↑    0.317073        0.0  0.073171  0.780488  0.170732  0.170732

           Chronos  TimeLLM  timesfm     Morai  Timer
99.5th ↑  0.500000      0.0      0.0  0.000000    0.0
90th ↑    0.536585      0.0      0.0  0.121951    0.0

In [17]:
print(sedi_df4.T)

              99.5th ↑    90th ↑
NBEATS             0.0  0.268293
Informer           0.0  0.512195
DLinear            0.5  0.487805
PatchTST           0.0  0.146341
iTransformer       0.0  0.243902
NLinear            0.0  0.121951
RMoK               0.0  0.317073
TimeMixer          0.0  0.000000
TSMixer            0.0  0.073171
TSMixerx           0.0  0.780488
KAN                0.0  0.170732
TimeGPT            0.0  0.170732
Chronos            0.5  0.536585
TimeLLM            0.0  0.000000
timesfm            0.0  0.000000
Morai              0.0  0.121951
Timer              0.0  0.000000

In [18]:
sedi_df4 = sedi_df4.drop("99.5th ↑", axis=0)
sedi_df4

,NBEATS,Informer,DLinear,PatchTST,iTransformer,NLinear,RMoK,TimeMixer,TSMixer,TSMixerx,KAN,TimeGPT,Chronos,TimeLLM,timesfm,Morai,Timer
90th ↑,0.268293,0.512195,0.487805,0.146341,0.243902,0.121951,0.317073,0.0,0.073171,0.780488,0.170732,0.170732,0.536585,0.0,0.0,0.121951,0.0

In [19]:
import pandas as pd
import numpy as np  # Make sure to import numpy

# Assuming df is your DataFrame
unique_id = 'NESRS2'

# Filter dataset for the unique_id
df_filtered = df[df['unique_id'] == unique_id]

# Extract actual and predicted values
y_true = df_filtered['y']
predicted_columns = ['NBEATS', 'Informer', 'DLinear', 'PatchTST', 'iTransformer', 'NLinear', 'RMoK', 
                     'TimeMixer', 'TSMixer', 'TSMixerx', 'KAN', 'TimeGPT', 'Chronos', 'TimeLLM', 'timesfm', 'Morai', 'Timer']

# Initialize dictionary to store SEDI values
sedi_results = {}

# Define function to calculate SEDI score for a given threshold
def calculate_sedi(true_values, predicted_values, low_threshold, high_threshold):
    yp_low = np.percentile(true_values, low_threshold * 100)
    yp_up = np.percentile(true_values, high_threshold * 100)

    numerator = 0
    denominator = 0
    
    # Loop through each prediction and calculate SEDI
    for true_value, pred_value in zip(true_values, predicted_values):
        true_extreme_low = true_value < yp_low
        true_extreme_up = true_value > yp_up
        pred_extreme_low = pred_value < yp_low
        pred_extreme_up = pred_value > yp_up
        
        if true_extreme_low:
            denominator += 1
        if true_extreme_up:
            denominator += 1
        if true_extreme_low and pred_extreme_low:
            numerator += 1
        if true_extreme_up and pred_extreme_up:
            numerator += 1
    
    # Return SEDI score, avoiding division by zero
    return numerator / denominator if denominator != 0 else 0

# Define percentiles to calculate SEDI for
percentiles = [0.995, 0.90]

# Initialize a dictionary to store SEDI scores for each model and unique_id
sedi_scores_by_id = {}

# Calculate SEDI scores for each model at 99.5th and 90th percentiles
for model in predicted_columns:
    model_scores = []
    for p in percentiles:
        sedi_score = calculate_sedi(y_true, df_filtered[model], 1 - p, p)
        model_scores.append(sedi_score)
    sedi_scores_by_id[model] = model_scores

# Store the calculated SEDI scores for this unique_id
sedi_results[unique_id] = sedi_scores_by_id

# Convert to DataFrame for easy visualization
sedi_df5 = pd.DataFrame(sedi_results[unique_id], index=[f"99.5th ↑", f"90th ↑"])
print(sedi_df5)

            NBEATS  Informer   DLinear  PatchTST  iTransformer   NLinear  \
99.5th ↑  0.000000       0.0  0.666667  0.000000      0.000000  0.000000
90th ↑    0.285714       0.5  0.500000  0.190476      0.595238  0.166667

              RMoK  TimeMixer   TSMixer  TSMixerx       KAN   TimeGPT  \
99.5th ↑  0.000000        0.0  0.000000   0.00000  0.000000  0.000000
90th ↑    0.309524        0.0  0.095238   0.47619  0.190476  0.166667

           Chronos  TimeLLM  timesfm    Morai  Timer
99.5th ↑  0.666667      0.0      0.0  0.00000    0.0
90th ↑    0.761905      0.0      0.0  0.02381    0.0

In [20]:
print(sedi_df5.T)

              99.5th ↑    90th ↑
NBEATS        0.000000  0.285714
Informer      0.000000  0.500000
DLinear       0.666667  0.500000
PatchTST      0.000000  0.190476
iTransformer  0.000000  0.595238
NLinear       0.000000  0.166667
RMoK          0.000000  0.309524
TimeMixer     0.000000  0.000000
TSMixer       0.000000  0.095238
TSMixerx      0.000000  0.476190
KAN           0.000000  0.190476
TimeGPT       0.000000  0.166667
Chronos       0.666667  0.761905
TimeLLM       0.000000  0.000000
timesfm       0.000000  0.000000
Morai         0.000000  0.023810
Timer         0.000000  0.000000

In [21]:
sedi_df5 = sedi_df5.drop("99.5th ↑", axis=0)
sedi_df5

,NBEATS,Informer,DLinear,PatchTST,iTransformer,NLinear,RMoK,TimeMixer,TSMixer,TSMixerx,KAN,TimeGPT,Chronos,TimeLLM,timesfm,Morai,Timer
90th ↑,0.285714,0.5,0.5,0.190476,0.595238,0.166667,0.309524,0.0,0.095238,0.47619,0.190476,0.166667,0.761905,0.0,0.0,0.02381,0.0

In [22]:
# Transpose the DataFrames and add the station name as a top-level column
sedi_df1_t = sedi_df1.T
sedi_df1_t.columns = pd.MultiIndex.from_product([['NP205_stage'], sedi_df1_t.columns])

sedi_df2_t = sedi_df2.T
sedi_df2_t.columns = pd.MultiIndex.from_product([['P33_stage'], sedi_df2_t.columns])

sedi_df3_t = sedi_df3.T
sedi_df3_t.columns = pd.MultiIndex.from_product([['G620_stage'], sedi_df3_t.columns])

sedi_df4_t = sedi_df4.T
sedi_df4_t.columns = pd.MultiIndex.from_product([['NESRS1'], sedi_df4_t.columns])

sedi_df5_t = sedi_df5.T
sedi_df5_t.columns = pd.MultiIndex.from_product([['NESRS2'], sedi_df5_t.columns])

# Concatenate all transposed DataFrames along the columns
merged_sedi_df = pd.concat([sedi_df1_t, sedi_df2_t, sedi_df3_t, sedi_df4_t, sedi_df5_t], axis=1)

# Print the resulting DataFrame
print(merged_sedi_df)

             NP205_stage P33_stage G620_stage    NESRS1    NESRS2
                  90th ↑    90th ↑     90th ↑    90th ↑    90th ↑
NBEATS          0.261905  0.268293   0.463415  0.268293  0.285714
Informer        0.500000  0.487805   0.487805  0.512195  0.500000
DLinear         0.261905  0.512195   0.390244  0.487805  0.500000
PatchTST        0.190476  0.146341   0.195122  0.146341  0.190476
iTransformer    0.142857  0.243902   0.243902  0.243902  0.595238
NLinear         0.142857  0.121951   0.146341  0.121951  0.166667
RMoK            0.119048  0.097561   0.170732  0.317073  0.309524
TimeMixer       0.119048  0.048780   0.341463  0.000000  0.000000
TSMixer         0.142857  0.146341   0.195122  0.073171  0.095238
TSMixerx        0.380952  0.829268   0.829268  0.780488  0.476190
KAN             0.119048  0.073171   0.341463  0.170732  0.190476
TimeGPT         0.023810  0.195122   0.195122  0.170732  0.166667
Chronos         0.785714  0.658537   0.804878  0.536585  0.761905
TimeLLM         0.000000  0.000000   0.000000  0.000000  0.000000
timesfm         0.095238  0.024390   0.170732  0.000000  0.000000
Morai           0.476190  0.317073   0.487805  0.121951  0.023810
Timer           0.000000  0.000000   0.000000  0.000000  0.000000

In [23]:
import pandas as pd

# Create the DataFrame
data = {
    'NP205_stage': [0.261905, 0.500000, 0.261905, 0.190476, 0.142857, 0.142857, 0.119048, 0.119048, 0.142857, 0.380952, 0.119048, 0.023810, 0.785714, 0.000000, 0.095238, 0.476190, 0],
    'P33_stage': [0.268293, 0.487805, 0.512195, 0.146341, 0.243902, 0.121951, 0.097561, 0.048780, 0.146341, 0.829268, 0.073171, 0.195122, 0.658537, 0.000000, 0.024390, 0.317073, 0],
    'G620_stage': [0.463415, 0.487805, 0.390244, 0.195122, 0.243902, 0.146341, 0.170732, 0.341463, 0.195122, 0.829268, 0.341463, 0.195122, 0.804878, 0.000000, 0.170732, 0.487805, 0],
    'NESRS1': [0.268293, 0.512195, 0.487805, 0.146341, 0.243902, 0.121951, 0.317073, 0.000000, 0.073171, 0.780488, 0.170732, 0.170732, 0.536585, 0.000000, 0.000000, 0.121951, 0],
    'NESRS2': [0.285714, 0.500000, 0.500000, 0.190476, 0.595238, 0.166667, 0.309524, 0.000000, 0.095238, 0.476190, 0.190476, 0.166667, 0.761905, 0.000000, 0.000000, 0.023810, 0]
}

index = [
    "NBEATS", "Informer", "DLinear", "PatchTST", "iTransformer", "NLinear", 
    "RMoK", "TimeMixer", "TSMixer", "TSMixerx", "KAN", "TimeGPT", 
    "Chronos", "TimeLLM", "timesfm", "Morai", "Timer"
]

# Create the DataFrame
df7 = pd.DataFrame(data, index=index)

# Add the "Overall" column (mean across all stages for each row)
df7["Overall"] = df7.mean(axis=1)

# Display the updated DataFrame
print(df7)

              NP205_stage  P33_stage  G620_stage    NESRS1    NESRS2   Overall
NBEATS           0.261905   0.268293    0.463415  0.268293  0.285714  0.309524
Informer         0.500000   0.487805    0.487805  0.512195  0.500000  0.497561
DLinear          0.261905   0.512195    0.390244  0.487805  0.500000  0.430430
PatchTST         0.190476   0.146341    0.195122  0.146341  0.190476  0.173751
iTransformer     0.142857   0.243902    0.243902  0.243902  0.595238  0.293960
NLinear          0.142857   0.121951    0.146341  0.121951  0.166667  0.139953
RMoK             0.119048   0.097561    0.170732  0.317073  0.309524  0.202788
TimeMixer        0.119048   0.048780    0.341463  0.000000  0.000000  0.101858
TSMixer          0.142857   0.146341    0.195122  0.073171  0.095238  0.130546
TSMixerx         0.380952   0.829268    0.829268  0.780488  0.476190  0.659233
KAN              0.119048   0.073171    0.341463  0.170732  0.190476  0.178978
TimeGPT          0.023810   0.195122    0.195122  0.170732  0.166667  0.150291
Chronos          0.785714   0.658537    0.804878  0.536585  0.761905  0.709524
TimeLLM          0.000000   0.000000    0.000000  0.000000  0.000000  0.000000
timesfm          0.095238   0.024390    0.170732  0.000000  0.000000  0.058072
Morai            0.476190   0.317073    0.487805  0.121951  0.023810  0.285366
Timer            0.000000   0.000000    0.000000  0.000000  0.000000  0.000000